networks:
  default:
    name: ds-network

services:
  mysql:
    image: mysql:5.7.38
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - ~/.docker-service/mysql/conf:/etc/mysql/conf.d
      - ~/.docker-service/mysql/data:/var/lib/mysql
      - ~/.docker-service/mysql/logs:/logs
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
#      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 10s
      timeout: 20s
      retries: 10
