networks:
  default:
    name: ds-network

services:
  redis:
    image: redis:5.0.7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ~/.docker-service/redis:/data
    command: redis-server --appendonly yes
