networks:
  default:
    name: ds-network

services:
  zookeeper:
    image: zookeeper:3.8.0
    restart: unless-stopped
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    volumes:
      - ~/.docker-service/zookeeper/data:/data
      - ~/.docker-service/zookeeper/conf:/conf
      - ~/.docker-service/zookeeper/logs:/datalog
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181
    healthcheck:
      test: [ "CMD", "zkServer.sh" ,"status" ]
      interval: 10s
      timeout: 20s
      retries: 10